---
- name: Add Prometheus Helm repository
  command: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
  notify: 
    - Update Helm repositories

- name: Update Helm repositories
  command: helm repo update

- name: Install
  kubernetes.core.helm:
    name: kube-prometheus-stack
    chart_ref: prometheus-community/kube-prometheus-stack
    release_namespace: "{{ app_namespace }}"
    create_namespace: true
    values:
      grafana:
        adminPassword: "{{ user_password }}"
        ingress:
          enabled: true
          annotations:
            nginx.ingress.kubernetes.io/proxy-buffer-size: "32k"
            nginx.ingress.kubernetes.io/affinity: "cookie"
            nginx.ingress.kubernetes.io/rewrite-target: /
            nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
            nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
            nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
            nginx.ingress.kubernetes.io/proxy-body-size: "512m"
            kubernetes.io/ingress.class: "nginx"
            cert-manager.io/cluster-issuer: grafissuer
            nginx.ingress.kubernetes.io/ssl-redirect: "true"
            nginx.ingress.kubernetes.io/ssl-passthrough: "true"
          hosts:
            - "{{ app_host }}"
      prometheus:
        ingress:
          enabled: true
          annotations:
            nginx.ingress.kubernetes.io/proxy-buffer-size: "32k"
            nginx.ingress.kubernetes.io/affinity: "cookie"
            nginx.ingress.kubernetes.io/rewrite-target: /
            nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
            nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
            nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
            nginx.ingress.kubernetes.io/proxy-body-size: "512m"
            kubernetes.io/ingress.class: "nginx"
            cert-manager.io/cluster-issuer: promissuer
            nginx.ingress.kubernetes.io/ssl-redirect: "true"
            nginx.ingress.kubernetes.io/ssl-passthrough: "true"
          hosts:
            - "{{ app_host }}"
        state: present

  handlers:
    - name: Update Helm repositories
      command: helm repo update

