- name: Clone repository
  git:
    repo: https://github.com/prometheus-community/helm-charts.git
    dest: "{{ chart_path }}"

- name: Add Helm repository
  command: helm repo add bitnami https://charts.bitnami.com/bitnami
  notify: 
    - Update Helm repositories

- name: Build Helm chart dependencies
  command: helm dependency build
  args:
    chdir: "{{ chart_path }}/helm/defectdojo"

- name: Install
  kubernetes.core.helm:
    grafana:
      namespaceOverride: grafana
      adminPassword: "{{ user_password }}"
      ingress:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/proxy-buffer-size: "32k"
          nginx.ingress.kubernetes.io/affinity: "cookie"
          nginx.ingress.kubernetes.io/rewrite-target: /
          nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
          nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
          nginx.ingress.kubernetes.io/proxy-body-size: "512m"
          kubernetes.io/ingress.class: "nginx"
          cert-manager.io/cluster-issuer: grafissuer
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          nginx.ingress.kubernetes.io/ssl-passthrough: "true"
          kubernetes.io/tls-acme: "true"
    # kubeconfig: "{{ kubeconfig }}"
    # name: defectdojo
    # chart_ref: "{{ chart_path }}/helm/defectdojo"
    # state: present
    # release_namespace: "{{ app_namespace }}"
    # create_namespace: true
    # release_state: present
    # values:
    #   createSecret: true
    #   createRedisSecret: true
    #   createPostgresqlSecret: true
    #   host: "{{ app_host }}"
    #   admin:
    #     user: "{{ user_name }}"
    #     password: "{{ user_password }}"
    #     mail: "{{ user_email }}"
      postgresql:
        enabled: false
        postgresServer: "{{ db_host }}"
        auth:
          username: "{{ db_username }}"
          password: "{{ db_password }}"
          database: "{{ db_name }}"
