- name: Add Helm repository
  kubernetes.core.helm_repository:
    kubeconfig: "{{ kubeconfig }}"
    name: jetstack
    repo_url: https://charts.jetstack.io
    state: present
  notify: Initialize Helm client

- name: Install cert-manager
  kubernetes.core.helm:
    kubeconfig: "{{ kubeconfig }}"
    name: jetstack
    chart_ref: jetstack/cert-manager
    state: present
    release_namespace: cert-manager
    create_namespace: true
    release_state: present
    values:
      installCRDs: true