name: App deploy workflow

on:
  push:
    tags:
      - v*
    # paths:
    #   - '.github/workflows/**'

jobs:
  ingress-nginx:
    name: "Deploy ingress-nginx"
    uses: ./.github/workflows/actions.yml
    with:
        PLAYBOOK: "ingress-nginx.yml"

  cert-manager:
    name: "Deploy cert-manager"
    uses: ./.github/workflows/actions.yml
    with:
        PLAYBOOK: "cert-manager.yml"

  clusterissuer-grafana:
    name: "Deploy clusterissuer-grafana"
    needs: cert-manager
    uses: ./.github/workflows/actions.yml
    with:
        PLAYBOOK: "clusterissuer.yml"
        APP_HOST: ${{ vars.GRAFANA_HOST }}
        APP_NAMESPACE: ${{ vars.GRAFANA_NAMESPACE }}
        NAME_CLUSTERISSUER: "grafissuer"
        CHART_PATH: ${{ github.workspace }}/clusterissuer

  grafana:
    name: "Deploy grafana"
    needs: clusterissuer-grafana
    uses: ./.github/workflows/actions.yml
    with:
        APP_HOST: ${{ vars.GRAFANA_HOST }}
        APP_NAMESPACE: ${{ vars.GRAFANA_NAMESPACE }}
        PLAYBOOK: "defectdojo.yml"
    secrets:
        USER_PASSWORD: ${{ secrets.GRAFANA_PASSWORD }}
