name: App deploy workflow

on:
  workflow_call:
    inputs:
      APP_NAMESPACE:
        required: false
        type: string
    secrets:
      USER_NAME:
        required: true
      USER_PASSWORD:
        required: true
      DIGITALOCEAN_ACCESS_TOKEN:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      
      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ vars.K8S_CLUSTER_NAME }}

      - name: Check Kubernetes context
        run: kubectl create secret generic basic-auth prometheus-basic-auth --namespace monitoring ${{ inputs.APP_NAMESPACE }} \
               --from-literal=username=${{ secrets.USER_NAME }} \
               --from-literal=password=${{ secrets.USER_PASSWORD }}
